feat: homebrew on image
ublue-os/bluefin pull request #1293
Opened 2024-05-12 19:16 UTC by m2Giles

2024-05-12 19:44 UTC, m2Giles commented
ToDo:

Better handling of permissions for lower to upper directory.

Right now the lower dir is owned by root. How do we make sure that brew can modify things without making duplicates of everything in the mutable upper directory. Or if duplication is fine getting that immediate chown fired.

But brew is on image.

2024-05-13 14:21 UTC, m2Giles commented
Root can use homebrew binaries if you have an interactive login shell.

For systemd services you can specify the binary with the full path. So something like rclone would be /home/linuxbrew/.linuxbrew/bin/rclone instead of /usr/bin/rclone.

2024-05-13 16:44 UTC, m2Giles commented
We'll need to adjust the brew just commands from config to not mess with this.

2024-05-13 20:31 UTC, m2Giles commented
Assumptions made:
1. The brew user is UID 1000. This makes sense for our systems:
    1. The Bluefin ISO will create the first user as a wheel user and UID 1000.
    1. The Aurora ISO needs the user to go into the advanced options to change the UID.
1. Single User system.
    1. Brew expects to be owned by a single user. Since most of our systems are single user our setup should be fine. However, for a multi-user system, UID 1000 needs to be the brew user.
1. Auto Updates
    1. Brew controls if it should auto-update based on an environment variable. Since brew and the portable ruby are on image, we do not want this to occur. This means that if a user goes awhile without rebooting, brew will not update.
    1. Need to inspect how auto upgrades work since normally you update prior to running upgrade.

2024-05-13 21:22 UTC, castrojo requested changes

2024-05-13 21:22 UTC, castrojo commented on system_files/kinoite/usr/share/ublue-os/motd/bluefin.md
> +| `ujust bluefin-cli` | Install Terminal Bling w/ Brew |
```suggestion
| `ujust bluefin-cli` | Enable terminal bling | 
```

2024-05-13 21:22 UTC, castrojo commented on system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
> +| `ujust bluefin-cli` | Install Terminal Bling w/ Brew |
```suggestion
| `ujust bluefin-cli` | Enable terminal bling | 
```

2024-05-13 21:22 UTC, castrojo commented on just/bluefin-system.just
> +
```suggestion
bluefin-cli:
    brew bundle --file /usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
    echo `Installation complete ... please close and reopen your terminal!`
```

2024-05-16 01:13 UTC, m2Giles commented
Switching from the downloaded version of homebrew to the version installed by bluefin-cli, drops the duplicated data size down to 20 MB.

2024-05-16 01:45 UTC, castrojo approved these changes

2024-05-16 01:45 UTC, merged

2024-05-16 01:53 UTC, m2Giles commented
https://github.com/ublue-os/bluefin/pull/1301

This needs to be added.