feat: ensure firefox (flatpak) has hardware decoding turned on by default
ublue-os/bluefin pull request #1876
Opened 2024-11-04 02:34 UTC by tulilirockz

Got this straight from Bazzite, just renamed a few thingies to make it Bluefin-themed :p - Fixes #1730

2024-11-05 23:19 UTC, bsherman commented
I'm not sure about all these settings... I don't think they are required to enable hardware accelerated video decoding.

I don't have any of them and hw accel decode works well for me. (I happen to have been testing this topic lately).

2024-11-07 04:40 UTC, bsherman requested changes
I think we can go with this if it's only the `01-bluefin-global.js` for now.

I've been testing hardware acceleration a lot this past week. So while I do want us to default enable `media.ffmpeg.vaapi.enabled` and `gfx.webrender.all` is also probably fine, I'm hesitant on the other changes just yet.

2024-11-07 04:40 UTC, bsherman commented on system_files/silverblue/usr/share/ublue-os/firefox-config/03-bluefin-gnome.js
Let's skip this file for now as I'd like to do small, targeted changes and at the least, the rounded corner setting has nothing to do with hw accerlation.

2024-11-07 18:44 UTC, tulilirockz commented on system_files/silverblue/usr/share/ublue-os/firefox-config/03-bluefin-gnome.js
True! Lemme just fix this thing then

2024-11-07 19:39 UTC, bsherman approved these changes
Thank you!

2024-11-07 20:37 UTC, merged