chore(just): make aliases into recipes to get autocompletion
ublue-os/bluefin pull request #1914
Opened 2024-11-10 03:11 UTC by tulilirockz

Should fix #1805

2024-11-10 04:42 UTC, m2Giles commented
We should also use this as an opportunity to clean up stale ones.

2024-11-10 11:07 UTC, castrojo commented on just/bluefin-system.just
> +switch-channel:
```suggestion
switch-stream:
```

2024-11-10 11:08 UTC, castrojo commented on just/bluefin-system.just
> +switch-channels:
```suggestion
switch-streams:
```

2024-11-10 11:08 UTC, castrojo requested changes

2024-11-10 11:08 UTC, castrojo commented on just/bluefin-system.just
> +switch-channels:
coreos calls these streams

2024-11-10 15:41 UTC, m2Giles commented
when working with the justfiles. Please be sure to run `just fix`. We run `just check` as part of the workflow to make sure we don't ship broken justfiles.

2024-11-13 04:33 UTC, tulilirockz commented
Should I also include a move to bootc on this PR? I am thinking about refactoring most of these scripts to not use rpm-ostree and instead use a wrapper over bootc that allows it to run rootless (ubootc or something)

2024-11-13 05:10 UTC, tulilirockz commented
The indentation on some places also seems a bit funky, ill be reformatting them to always fit 4 spaces indentation

2024-11-13 05:32 UTC, castrojo commented
> Should I also include a move to bootc on this PR? 

Follow on PRs are always better instead of conflating things. 

> a wrapper over bootc that allows it to run rootless (ubootc or something)

This is out of scope for us, we're trying to delete as much of our custom stuff as possible these days.

2024-11-13 18:11 UTC, m2Giles commented on just/bluefin-system.just
> +switch-streams:
just alias this.

2024-11-14 00:52 UTC, tulilirockz commented
Then we could regroup stuff, honestly I feel like separating it in `apps`, `tools` and `system` doesnt seem like the best? `apps` and `tools` could be the same category (`tools`)

2024-11-17 16:12 UTC, castrojo commented
We need to keep jetbrains (people comment about how useful this is all the time), and the tailscale toggle was an ask in the survey. So let's keep that for people who use other VPNs. Not sure on invokeai so let's keep it for now. We can always do another pass.

2024-11-17 16:22 UTC, castrojo commented
OK one final pass from others would be appreciated on this one! (I know m2 wanted one more look).

2024-11-17 20:16 UTC, tulilirockz commented
Alright, so, after manually testing every single one of the affected recipes, they all seem to work fine, without any major changes. The only ones that I saw that were broken were the toggle-tailscale and setup-ollama ones - just reverted them. The tailscale one also didnt seem to toggle the extension on the `Silverblue` $VARIANT so I just made it uppercase :p

2024-11-18 18:18 UTC, castrojo approved these changes

2024-11-18 18:51 UTC, merged